#!/bin/bash

drush mim --execute-dependencies d7_dblog_settings
drush mim --execute-dependencies d7_file_private
drush mim --execute-dependencies d7_filter_settings
drush mim --execute-dependencies d7_global_theme_settings
drush mim --execute-dependencies d7_image_settings
drush mim --execute-dependencies d7_image_styles
drush mim --execute-dependencies d7_node_settings
drush mim --execute-dependencies d7_path_redirect
drush mim --execute-dependencies d7_pathauto_settings
drush mim --execute-dependencies d7_search_settings
drush mim --execute-dependencies d7_system_authorize
drush mim --execute-dependencies d7_system_cron
drush mim --execute-dependencies d7_system_date
drush mim --execute-dependencies d7_system_file
drush mim --execute-dependencies d7_system_mail
drush mim --execute-dependencies d7_system_performance
drush mim --execute-dependencies d7_theme_settings
drush mim --execute-dependencies d7_user_flood
drush mim --execute-dependencies d7_user_mail
drush mim --execute-dependencies d7_user_settings
drush mim --execute-dependencies d7_field_collection_type
drush mim --execute-dependencies d7_filter_format
drush mim --execute-dependencies d7_custom_block
drush mim --execute-dependencies d7_user_role
drush mim --execute-dependencies d7_block
drush mim --execute-dependencies d7_field
drush mim --execute-dependencies d7_node_type
drush mim --execute-dependencies d7_taxonomy_vocabulary
drush mim --execute-dependencies d7_field_instance
drush mim --execute-dependencies d7_view_modes
drush mim --execute-dependencies d7_field_formatter_settings
drush mim --execute-dependencies d7_field_instance_widget_settings
drush mim --execute-dependencies d7_field_group:node:page
drush mim --execute-dependencies d7_field_group:node:map_page
drush mim --execute-dependencies d7_field_group:node:country
drush mim --execute-dependencies d7_field_group:node:country_score
drush mim --execute-dependencies d7_field_group:node:partner
drush mim --execute-dependencies d7_field_group:node:webform
drush mim --execute-dependencies d7_field_group:field_collection_item:field_indicators
drush mim --execute-dependencies d7_field_group:field_collection_item:field_compare
drush mim --execute-dependencies d7_file
drush mim --execute-dependencies d7_menu
drush mim --execute-dependencies d7_user
drush mim --execute-dependencies d7_node_complete:addresses
drush mim --execute-dependencies d7_field_collection:country_data
drush mim --execute-dependencies d7_field_collection:indicators
drush mim --execute-dependencies d7_field_collection:paragraph_images
drush mim --execute-dependencies d7_field_collection:introduction
drush mim --execute-dependencies d7_field_collection:lists
drush mim --execute-dependencies d7_field_collection:lists_full_width
drush mim --execute-dependencies d7_field_collection:compare
drush mim --execute-dependencies d7_field_collection_revisions:country_data
drush mim --execute-dependencies d7_node_complete:country
drush mim --execute-dependencies d7_field_collection_revisions:indicators
drush mim --execute-dependencies d7_node_complete:country_score
drush mim --execute-dependencies d7_field_collection_revisions:compare
drush mim --execute-dependencies d7_node_complete:map_page
drush mim --execute-dependencies d7_field_collection_revisions:introduction
drush mim --execute-dependencies d7_field_collection_revisions:lists
drush mim --execute-dependencies d7_field_collection_revisions:lists_full_width
drush mim --execute-dependencies d7_node_complete:page
drush mim --execute-dependencies d7_node_complete:partner
drush mim --execute-dependencies d7_node_complete:webform
drush mim --execute-dependencies d7_menu_links
drush mim --execute-dependencies d7_node:addresses
drush mim --execute-dependencies d7_node:country
drush mim --execute-dependencies d7_node:country_score
drush mim --execute-dependencies d7_node:map_page
drush mim --execute-dependencies d7_node:page
drush mim --execute-dependencies d7_node:partner
drush mim --execute-dependencies d7_node:webform
drush mim --execute-dependencies d7_node_revision:addresses
drush mim --execute-dependencies d7_node_revision:country
drush mim --execute-dependencies d7_node_revision:country_score
drush mim --execute-dependencies d7_node_revision:map_page
drush mim --execute-dependencies d7_node_revision:page
drush mim --execute-dependencies d7_node_revision:partner
drush mim --execute-dependencies d7_node_revision:webform
drush mim --execute-dependencies d7_node_title_label
drush mim --execute-dependencies d7_url_alias
drush mim --execute-dependencies d7_rdf_mapping
drush mim --execute-dependencies d7_taxonomy_term:goals
drush mim --execute-dependencies d7_taxonomy_term:indicators
drush mim --execute-dependencies d7_taxonomy_term:score
drush mim --execute-dependencies d7_taxonomy_term:years
drush mim --execute-dependencies d7_taxonomy_term:regions
drush mim --execute-dependencies d7_taxonomy_term:partner_type
drush mim --execute-dependencies d7_taxonomy_term:verification_titles
drush mim --execute-dependencies d7_taxonomy_term:score_comparison
drush mim --execute-dependencies d7_pathauto_patterns
drush mim --execute-dependencies d7_field_collection_revisions:paragraph_images

